config/routes.rb
Rails.application.routes.draw do
  resources :cart_items
  resources :carts
  get "static_pages/home"
  get "static_pages/contact"
  get "stores/index"

  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "stores#index", as: :store
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

# creating cart items instance with association method in rails console
# product = Product.first
# cart = Cart.first
# cart_item = cart.cart_items.new(product: product)
# cart_item.save()

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create] #is in current_cart.rb
  #creates cart and store in session .
  before_action :set_cart_item, only: %i[ show edit update destroy ]

  # GET /cart_items or /cart_items.json
  def index
    @cart_items = CartItem.all
  end

  # GET /cart_items/1 or /cart_items/1.json
  def show
  end

  # GET /cart_items/new
  def new
    @cart_item = CartItem.new
  end

  # GET /cart_items/1/edit
  def edit
  end

  # POST /cart_items or /cart_items.json
  def create
    product = Product.find(params[:product_id])
    #received from params in store/index.html.erb button add to cart
    @cart_item = @cart.add_product(product) #add_product is defined in cart.rb
    #here @cart is extracted from concern current_cart

    respond_to do |format|
      if @cart_item.save
        format.html { redirect_to store_path, notice: "Cart item was successfully created." }
        # format.html { redirect_to cart_path(@cart), notice: "Cart item was successfully created." }
        #to in the above commented line (@cart) is directly received from set_cart method and above cart id is received from association in cart_items.rb
        format.json { render :show, status: :created, location: @cart_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cart_items/1 or /cart_items/1.json
  def update
    respond_to do |format|
      if @cart_item.update(cart_item_params)
        format.html { redirect_to @cart_item, notice: "Cart item was successfully updated." }
        format.json { render :show, status: :ok, location: @cart_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cart_items/1 or /cart_items/1.json
  def destroy
    @cart_item.destroy!

    respond_to do |format|
      format.html { redirect_to cart_path, status: :see_other, notice: "Cart item was successfully removed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cart_item
    @cart_item = CartItem.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cart_item_params
    params.require(:cart_item).permit(:product_id, :cart_id)
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/_cart_item.html.erb
<div id="<%= dom_id cart_item %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Product:</strong>
    <%= cart_item.product_id %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Cart:</strong>
    <%= cart_item.cart_id %>
  </p>
</div>

app/views/cart_items/_form.html.erb
<%= form_with(model: cart_item, class: "contents") do |form| %>
  <% if cart_item.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(cart_item.errors.count, "error") %> prohibited this cart_item from being saved:</h2>

      <ul class="list-disc ml-6">
        <% cart_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :product_id %>
    <%= form.text_field :product_id, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": cart_item.errors[:product_id].none?, "border-red-400 focus:outline-red-600": cart_item.errors[:product_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": cart_item.errors[:cart_id].none?, "border-red-400 focus:outline-red-600": cart_item.errors[:cart_id].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/cart_items/edit.html.erb
<% content_for :title, "Editing cart item" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing cart item</h1>

  <%= render "form", cart_item: @cart_item %>

  <%= link_to "Show this cart item", @cart_item, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to cart items", cart_items_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/cart_items/index.html.erb
<% content_for :title, "Cart items" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Cart items</h1>
    <%= link_to "New cart item", new_cart_item_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="cart_items" class="min-w-full">
    <% if @cart_items.any? %>
      <% @cart_items.each do |cart_item| %>
        <%= render cart_item %>
        <p>
          <%= link_to "Show this cart item", cart_item, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
        </p>
      <% end %>
    <% else %>
      <p class="text-center my-10">No cart items found.</p>
    <% end %>
  </div>
</div>

app/views/cart_items/new.html.erb
<% content_for :title, "New cart item" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New cart item</h1>

  <%= render "form", cart_item: @cart_item %>

  <%= link_to "Back to cart items", cart_items_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/cart_items/show.html.erb
<% content_for :title, "Showing cart item" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing cart item</h1>

  <%= render @cart_item %>

  <%= link_to "Edit this cart item", edit_cart_item_path(@cart_item), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to cart items", cart_items_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this cart item", @cart_item, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" %>
  </div>
</div>