config/routes.rb
Rails.application.routes.draw do
  resources :cart_items
  resources :carts
  get "static_pages/home"
  get "static_pages/contact"
  get "stores/index"

  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "stores#index", as: :store
end

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Pragprog Books Online Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", media: "all",
    "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" %>
    <%= javascript_importmap_tags %>
  </head>
  <body data-turbo-track="reload">
    <%= debug(params) if Rails.env.development? %>
    <header class="bg-green-700">
      <%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf' %>
      <h1><%= @page_title %></h1>
    </header>
    <section class="flex">
      <nav class="bg-green-900 p-6">
        <div>
          <%= render partial:"carts/cart",locals:{cart: current_cart} %>
        </div>
        <ul class="text-gray-300 leading-8">
          <li><%= link_to "Home", store_path, class: "hover:bg-green-300 transition-colors duration-200" %></li>
          <li><%= link_to "Questions" ,"#"%></li>
          <li><%= link_to "News" ,"#"%></li>
          <li><%= link_to "Contact","#" %></li>
        </ul>
      </nav>
      <main class="container mx-auto mt-4 px-5 flex">
        <%= yield %>
      </main>
    </section>
  </body>
</html>